spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:37076/railway
    username: postgres
    password: DvbLjnzswsZaBeQPJRfCZeZcyddKDpbA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB
upload:
  path: /data/uploads #/Users/shahruhisaev/Documents/appstoryimages #
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    config-url: /shop-service/v3/api-docs/swagger-config
    url: /shop-service/v3/api-docs
    csrf:
      enabled: true
jwt:
  accessTokenExpiration: '3600000'
  refreshTokenExpiration: '604800000'
  secret: JcSCqHyIBr8M2BF2bcSpn0ukRcUymML0hT8ubI0b2cgDxjkELtTABWaYzzdi3LGnLITqyCNzQ3WCetgwmPnDp1Ik3R5NoVeS2Pve17wMyj3EX2TmMdSjE2q9u7eqdpTZ8su3dWyVQzaLajmBD7sxa8W3mpyU3Sh99rz85L0
server:
  port: 8080