spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:37076/railway
    username: postgres
    password: DvbLjnzswsZaBeQPJRfCZeZcyddKDpbA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB
paypal:
  client:
#    id: AfQySflty7K-ye9gwxO-23vZXSls0_cz1pvR-rGeX2H1rhi1HTUF6NoTdqaQPSETFipm4u-00gg8xcvQ
#    secret: ELy30fKAvTUyjYxlX6ZQXYmk2Ef7u4sm6JgXpKUCcmHChbzKPyHlj0WMD74FNrFwZrSBGm25T5V4kYRo
    id: AdCM-yFy5c67JYLceDAdy2uoqaDuqf1iBPDNAGqHWmeNJNc_GYGlyL6MCY8EIifItsmAUAVcyEqF8Dk3
    secret: EDuOIusyGGE4Ew84XxM8GawUVZkWGqg2wMZeeIhKVnOayTVY0fJSsN8LRYJeVlQFdOIxz6Au6gJoYtya
  mode: live
  return-url: https://app-store-murex.vercel.app/payment/success
  cancel-url: https://app-store-murex.vercel.app/payment/cancel
  webhook-id: 7R026524EA328190C
upload:
  path: /data/uploads #/Users/shahruhisaev/Documents/appstoryimages #
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # Swagger сам добавит /shop-service
  swagger-ui:
    path: /swagger-ui  # Swagger сам добавит /shop-service
    url: /shop-service/v3/api-docs  # ВАЖНО! Правильный путь к OpenAPI JSON
    csrf:
      enabled: true
jwt:
  accessTokenExpiration: '3600000'
  refreshTokenExpiration: '604800000'
  secret: JcSCqHyIBr8M2BF2bcSpn0ukRcUymML0hT8ubI0b2cgDxjkELtTABWaYzzdi3LGnLITqyCNzQ3WCetgwmPnDp1Ik3R5NoVeS2Pve17wMyj3EX2TmMdSjE2q9u7eqdpTZ8su3dWyVQzaLajmBD7sxa8W3mpyU3Sh99rz85L0
server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /shop-service